export const AUTH_MESSAGES = {
  validation: {
    nameMin: 'Name must be at least 2 characters',
    emailInvalid: 'Invalid email address',
    passwordMin: 'Password must be at least 8 characters',
    passwordsNoMatch: "Passwords don't match",
  },
  ui: {
    createAccount: 'Create your account',
    subtitle: 'Start planning amazing trips with our AI-powered platform',
    continueWith: 'Continue with',
    orContinueEmail: 'or continue with email',
    fullName: 'Full name',
    emailAddress: 'Email address',
    password: 'Password',
    confirmPassword: 'Confirm password',
    agreeToTerms: 'I agree to the',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    createAccountBtn: 'Create account',
    creatingAccount: 'Creating account...',
    alreadyHaveAccount: 'Already have an account?',
    signIn: 'Sign in',
  },
  placeholders: {
    enterFullName: 'Enter your full name',
    enterEmail: 'Enter your email',
    createPassword: 'Create a password',
    confirmPassword: 'Confirm your password',
  },
} as const;
